<a href="https://colab.research.google.com/github/dilp90/Artificial_Intelligence_FIME/blob/main/3_Libraries_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Library Tutorial**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation, and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, and many operations are performed in compiled code for performance.

# **Exercise:**

Matrix Manipulation and Analysis with NumPy for Artificial Intelligence

# **Goal:**

To become familiar with the use of NumPy for matrix manipulation and analysis, a library that facilitates working with large volumes of data and neural networks in artificial intelligence projects.

**1. Import necessary libraries**

In [1]:
import numpy as np

**2. Create and explore matrices:**

* Create a 3x3 matrix with random values between 0 and 1:

In [2]:
matrix_a = np.random.rand(3, 3)
print("Matrix A:")
print(matrix_a)

Matrix A:
[[0.56763968 0.04590056 0.35855906]
 [0.56636567 0.88445656 0.09989047]
 [0.58265358 0.65256322 0.51917164]]


* Create an identity matrix of size 3x3:

In [3]:
identity_matrix = np.eye(3)
print("Identity matrix:")
print(identity_matrix)

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


* * Create a matrix of ones of size 2x4:

In [4]:
ones_matrix = np.ones((2, 4))
print("Ones matrix:")
print(ones_matrix)

Ones matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**3. Basic matrix operations:**

* Matrix addition: Create another 3x3 matrix and add it to the first one:

In [5]:
matrix_b = np.random.rand(3, 3)
sum_matrix = matrix_a + matrix_b
print("Sum of Matrices A and B:")
print(sum_matrix)

Sum of Matrices A and B:
[[1.25417073 0.758744   0.56238965]
 [0.80723175 1.2924942  0.21103963]
 [1.17249981 1.10279385 0.9229281 ]]


* * Matrix product (matrix multiplication):

In [6]:
product_matrix = np.dot(matrix_a, matrix_b)
print("Product of Matrices A and B:")
print(product_matrix)

Product of Matrices A and B:
[[0.61225286 0.58480165 0.26557467]
 [0.66078322 0.80959537 0.25408067]
 [0.86342156 0.91535812 0.40091338]]


* Transposition of a matrix:

In [7]:
transposed_matrix = np.transpose(matrix_a)
print(" Transposition of matrix A:")
print(transposed_matrix)

 Transposition of matrix A:
[[0.56763968 0.56636567 0.58265358]
 [0.04590056 0.88445656 0.65256322]
 [0.35855906 0.09989047 0.51917164]]


**4. Accessing and manipulating elements:**

* Access the element at row 2, column 3 of `matrix_a`:

In [8]:
element = matrix_a[1, 2]
print("Element in row 2, column 3 of A:", element)

Element in row 2, column 3 of A: 0.09989046566157


* Change the value in row 1, column 2 of matrix_a to 5:

In [9]:
matrix_a[0, 1] = 5
print("Matrix A with modified value:")
print(matrix_a)

Matrix A with modified value:
[[0.56763968 5.         0.35855906]
 [0.56636567 0.88445656 0.09989047]
 [0.58265358 0.65256322 0.51917164]]


**5. Statistical operations:**

* Calculate the maximum, minimum and mean values ​​of the matrix `matrix_a`:

In [10]:
print("Maximum value of A:", np.max(matrix_a))
print("Minimum value of A:", np.min(matrix_a))
print("Mean value of A:", np.mean(matrix_a))

Maximum value of A: 5.0
Minimum value of A: 0.09989046566157
Mean value of A: 1.0256999870350951


**6. Dimension reduction:**

* Converts a 2D (3x3) matrix into a 9-element (1D) vector:

In [11]:
flattened_matrix = matrix_a.flatten()
print("Matrix A to 1D vector:")
print(flattened_matrix)

Matrix A to 1D vector:
[0.56763968 5.         0.35855906 0.56636567 0.88445656 0.09989047
 0.58265358 0.65256322 0.51917164]


7. Practical Applications for AI:

* *Data Normalization*: Suppose you have a dataset with features (e.g., a 3x3 feature matrix). Normalize the values ​​in each column so that they have a mean of 0 and a standard deviation of 1.

In [14]:
# Sample data (3x3 matrix)
data = np.array([[10, 200, 3000],
[20, 250, 4000],
[30, 300, 5000]])

# Calculation of min and max by column
min_vals = np.min(data, axis=0)
max_vals = np.max(data, axis=0)

# Min-Max normalization
normalized_data = (data - min_vals) / (max_vals - min_vals)

print("Original data:")
print(data)
print("Normalized data:")
print(normalized_data)

Original data:
[[  10  200 3000]
 [  20  250 4000]
 [  30  300 5000]]
Normalized data:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


Sources:

*   https://numpy.org/devdocs/user/whatisnumpy.html#whatisnumpy





M.Sc. Daniel I. Lopez-Paez

Class: Artificial Intelligence

PE: Biomedical Engineering

FIME-UANL